version: 2
updates:

  # Automatically check for updates in framework CLIs for C3
  - package-ecosystem: "npm"
    directory: "/packages/create-cloudflare/src/frameworks"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    commit-message:
      prefix: "[C3] "