name: Check PR
on:
  pull_request_target
  # :
    # paths:
    #   - 'packages/create-cloudflare/src/frameworks/package.json'

jobs:
  get-bumped-framework:
    runs-on: ubuntu-latest
    outputs:
      bumped-framework-cli: ${{ steps.detect.outputs.result }}
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
      - name: Get PR description as string
        id: get-pr-description
        run: |
          str=$(sed 's/`/\`/g' <<EOF
            ${{ github.event.pull_request.body }}
          EOF
          )
          echo 'result<<EOF' >> $GITHUB_OUTPUT
          echo $str >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: detect-bumped-framework
        id: detect
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { default: getBumpedFrameworkCli } = await import('.github/get-c3-dependabot-bumped-framework.mjs')
            return getBumpedFrameworkCli(`${{ steps.get-pr-description.outputs.result }}`);

  print-bumped-framework:
    needs: get-bumped-framework
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "the bumped framework is ${{ needs.get-bumped-framework.outputs.bumped-framework-cli }}"