name: Generate changeset
on:
  pull_request_target
  # :
    # paths:
    #   - 'packages/create-cloudflare/src/frameworks/package.json'

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: true
    steps:
      - name: echo user
        run: echo ${{ github.event.user.login }}
      - name: echo labels
        run: echo ${{ toJson(github.event.labels) }}
      - name: echo contains dependencies
        run: echo ${{ contains(github.event.labels.*.name, 'dependencies') }}
      - name: show github context
        run: echo "${{ toJson(github) }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
      - name: Configure Git
        run: |
          git config --global user.email test-fdswgwetpl1235m@test.test
          git config --global user.name 'Github changeset workflow'
      - name: Generate changeset
        run: node .github/generate-changeset.mjs