name: Generate changeset
on:
  pull_request_target
  # :
    # paths:
    #   - 'packages/create-cloudflare/src/frameworks/package.json'

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
      - name: Configure Git
        run: |
          git config --global user.email test-fdswgwetpl1235m@test.test
          git config --global user.name 'Github changeset workflow'
      - name: Generate changeset
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_PAT_TOKEN }}
        run: node .github/generate-changeset.mjs ${{ github.event.number }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: ${{ github.ref }}
          amend: true
          force: true
          message: "[C3] Update frameworks cli dependencies"
          github_token: ${{ secrets.GITHUB_TOKEN }}
